
#------------------------------------------------------------------#
#                     MONGODB CONFIGURATION                        #
#------------------------------------------------------------------#
%test.quarkus.mongodb.hosts=
%test.quarkus.mongodb.database=
%test.quarkus.mongodb.credentials.auth-source=
%test.quarkus.mongodb.credentials.username=
%test.quarkus.mongodb.credentials.password=
%test.quarkus.mongodb.devservices.enabled=true

quarkus.mongodb.hosts=${MONGODB_HOST:localhost:27017}
quarkus.mongodb.database=${MONGODB_DATABASE:microchess}
quarkus.mongodb.credentials.auth-source=${MONGODB_AUTH_SOURCE:admin}
quarkus.mongodb.credentials.username=${MONGODB_USERNAME}
quarkus.mongodb.credentials.password=${MONGODB_PASSWORD}

#------------------------------------------------------------------#
#                       SMTP CONFIGURATION                         #
#------------------------------------------------------------------#
quarkus.mailer.host=${SMTP_HOST:smtp.gmail.com}
quarkus.mailer.port=${SMTP_PORT:587}
quarkus.mailer.start-tls=${SMTP_START_TLS:REQUIRED}
quarkus.mailer.username=${SMTP_USERNAME}
quarkus.mailer.password=${SMTP_PASSWORD}
quarkus.mailer.from=${SMTP_FROM}